branches:
  only:
  - master
language: c
sudo: required

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq ocaml ocaml-native-compilers

install:
- wget -qq https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
- export OPAMYES=1
# - opam switch 4.04.0
- opam init
- eval `opam config env`
- opam update
- opam install ocamlfind

script:
- autoconf
- ./configure
- make -j4
- make test
